version: "3"

services:
  postgres:
    container_name: aluraflix-db
    image: 'bitnami/postgresql'
    restart: always
    tty: true
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=aluraflix
    networks:
      - aluraflix-network
    ports:
      - "5432:5432"

networks:
  aluraflix-network:
    driver: bridge
